In [52]:
import numpy as np #importar libreria matematica
import matplotlib.pyplot as plt #libreria de plots
import sympy as sp #libreria simbolica

# CABLES

Hay 4 casos:
- cables con cargas puntuales
- cables con cargas distribuidas no uniformes
- cables con cargas distribuidas uniformes
- catenarias (cable donde la única carga es el peso propio del cable)

## PUNTOS CLAVES SOBRE CABLES

* LA TENSIÓN HORIZONTAL ES SIEMPRE LA MISMA, SE MANTIENE CONSTANTE
* Son elementos flexibles - solo trabajan a tracción

### CABLES CON CARGAS PUNTUALES

Los segmentos se consideran líneas rectas.
<br>
Cables con cargas puntuales en su longitud. El peso del cable es despreciable.
<br>
![title](E-cables-1.png)

Y, para encontrar los apoyos y las tensiones en cada uno de los segmentos, se puede recortar el sistema. La tensión que se dibuja sigue la dirección del siguiente segmento. Se pueden hacer DCL y análisis de cada recorte de manera separada según convenga.
<br>
![title](E-cables-2.png)

### CABLES CON CARGAS DISTRIBUIDAS NO UNIFORMES

La cuerda NO es una parábola.
<br>
Cables cuya carga distribuida no es uniforme a lo largo de su longitud. El peso del cable es despreciable.
<br>
![title](E-cables-3.png)
Se toma una porción del cable tomando en cuenta que uno de los lados es el punto más bajo de la cuerda. En este punto aseguramos que la única tensión es la horizontal $T_0$. Luego, en el otro extremo se tiene la Tensión $T$ de la cuerda. Luego, se tiene $w$ que es la resultante de la sección mostrada, ubicada en el centroide.
<br>
![title](E-cables-4.png)
<br>
Como el sistema está en equilibrio, se puede colocar todas las fuerzas involucradas: $T_0  T w$ de tal forma que se tiene una figura cerrada.
<br>
![title](E-cables-5.png)
<br>
Con este análisis se tiene que:
$$T=\sqrt{T_{0}^2+w^2}$$
$$tan\theta=\frac{w}{T_0}$$
$$T_{0}=Tcos(\theta)$$
$$w=Tsen(\theta)$$

### CABLES CON CARGAS DISTRIBUIDAS UNIFORMES

La cuerda SI es una parábola.
<br>
Cables con una carga distribuida uniforme. El peso del cable es despreciable.
<br>
![title](E-cables-6.png)
<br>
Se toma el punto C como el punto más bajo de la cuerda. Un punto D cualquiera. Al ser una parábola el centroide, y, la carga distribuida concentrada $W$ se encuentra definida por $W=w.x$ y se encuentra ubicada en la mitad, o, sea a $\frac{x}{2}$ sea de C o D.
<br>
Luego, se corta el cable entre C y D para un análisis separado.
<br>
![title](E-cables-7.png)
<br>
Haciendo momentos alrededor del punto D se tiene
$$\sum M_D=0=-T_{0}(y)+wx(\frac{x}{2})$$
donde $y$ es la distancia vertical entre D y C
$$y=\frac{w}{2T_{0}}x^2$$
Entonces, de una fórmula general de la parábola: $y=ax^2+bx+c$, los términos $b=0, c=0$<br>Del análisis de triángulo de equilibrio formado:
<br>
![title](E-cables-5.png)
<br>
Se tiene:
$$T=\sqrt{T_{0}^2+w^2}$$
$$tan\theta=\frac{w}{T_0}$$

#### CALCULANDO LA LONGITUD DEL CABLE
Tomando en consideración un diferencial de cable $\partial{L}$. Se tiene:
$$\partial{L}=\sqrt{\partial{x}^2+\partial{y}^2}$$
$$\partial{L}=\sqrt{\frac{\partial{x}^2}{\partial{x}^2}+\frac{\partial{y}^2}{\partial{x}^2}}\partial{x}$$
$$\partial{L}=\sqrt{1+(\frac{\partial{y}}{\partial{x}})^2}\partial{x}$$
por otro lado se tiene que:
$$y=\frac{w}{2T_{0}}x^2$$
$$\frac{\partial{y}}{\partial{x}}=\frac{w}{T_0}x$$
y utilizando el concepto de expansión binomial
$$\sqrt{1+a}=1+\frac{1}{2}a\pm\frac{1.3.5..(2n-3)}{2^{n}n!}a^n$$
y aplicando en:
$$L=\int_{x=0}^{x=x_B}\partial{L}=\int_{x=0}^{x=x_B}\sqrt{1+(\frac{\partial{y}}{\partial{x}})^2}\partial{x}$$
$$\int_{x=0}^{x=x_B}\sqrt{1+(\frac{w}{T_0}^{2}x^{2})}\partial{x}$$
$$\int_{x=0}^{x=x_B}(1+\frac{1}{2}\frac{w}{T_0}^{2}x^{2}-\frac{1}{8}\frac{w}{T_0}^{4}x^{4})\partial{x}$$
$$x+\frac{w}{6T_0}^{2}x^{3}-\frac{w}{40T_0}x^{5}\biggr\rvert_{0,x_B}$$
$$\Longrightarrow x_B+\frac{w}{6T_0}^{2}x_{B}^{3}-\frac{w}{40T_0}x_{B}^{5}$$

#### EJERCICIO DE APLICACIÓN

Sea el cable AB de $L=100[m]$ sometido a una carga distribuida $w=100[N/m]$. Tanto A yB se encuentran a la misma altura vertical. El punto más bajo del cable se encuentra a $5[m]$ debajo de la horizontal AB.
<br>
![title](E-cables-9.png)
<br>
Tomamos una porción del cable para el análisis, desde C el punto más bajo, hasta uno de los extremos:
<br>
![title](E-cables-8.png)
<br>
$$W=w*x$$
$$\sum M_A=0=-W(25)+T_{0}(5) \rightarrow eq1$$
$$T=\sqrt{T_{0}^2+W^2} \rightarrow eq2$$
$$\theta=tg^{-1}(\frac{W}{T_0}) \rightarrow eq3$$
Qué pasa si se quiere reducir la distancia del punto más bajo a 2[m]
$$T_{0}=\frac{W(25)}{2}\rightarrow eq4$$
$$T=\sqrt{T_{0}^2+W^2} \rightarrow eq5$$
Cuál es la longitud del cable, si le dejamos con 5[m] de altura vertical
$$L=x_{A}[1+\frac{2y^2}{3X_{A}^2}-\frac{2y^4}{5x_{A}^4}] \rightarrow eq6$$
Y, si al final solo tengo para comprar 75[m] de cable y le coloco en una distancia AB de 70[m], a la misma altura Cuál es el saco del cable.<br>Se resuelve la eq6 para $y$, se necesita arreglar la ecuación como un polinomio.
$$-\frac{L}{2}+x_{A}+\frac{2y^2}{3X_{A}}-\frac{2y^4}{5x_{A}^3}=0 \rightarrow eq7$$


In [55]:
#El análisis de la carga distribuida en la sección
w=100 #N/m
x=50*w #N
W=w*x
L=100 #[m]longitud del cable
xA=25 #[m]longitud desde C hasta A
y1=5 #[m]altura vertical 1
y2=2 #[m]altura vertical 2
AB=70
L2=75
xB=35

#Sumatoria de momentos alrededor de A, de la eq1
T0=W*25/y1 #la tensión horizontal T0
print('la tensión horizontal es [N] ', T0)
#de la eq2
TA=np.sqrt(T0**2+W**2)
print('la tensión en A es [N] ', TA)
#de la eq3
h=np.arctan((W/T0))
H=np.rad2deg(h)
print('el ángulo de la tensión en A es [deg] ', H)
#de la eq4
print('para reducir de 5 a 2[m] en la vertical')
T1=W*25/y2 #la tensión horizontal T0
TB=np.sqrt(T1**2+W**2)
P1=(T1*100/T0)-100 #porcentaje de diferencia T0
P2=(TB*100/TA)-100 #porcentaje de diferencia en TA
print('la tensión horizontal aumenta en [%]',P1, 'y la tensión en el punto A aumenta de [%]', P2)
# de eq6
S1=L*(1+(2/3)*(y1/xA)**2-(2/5)*(y1/xA)**4)
M1=S1*2 #ya que xA=xB
S2=L*(1+(2/3)*(y2/xA)**2-(2/5)*(y2/xA)**4)
M2=S2*2 #ya que xA=xB
print('la longitud del cable para saco de 5[m]', M1, 'la longitud del cable para saco de 2[m]', M2)
#de eq7
coeff1=[-(2/(5*xB**3)),0,(2/(3*xB)),0,xB-(L2/2)] #definiendo el polinomio
sol1=np.roots(coeff1)
coeff2=[(2/(3*xB)),0,xB-(L2/2)] #definiendo el polinomio
sol2=np.roots(coeff2)
print('(x^4) el saco del cable de 75[m] entre postes de 70[m]',sol1)
print('(x^2) el saco del cable de 75[m] entre postes de 70[m]',sol2)

     

la tensión horizontal es [N]  2500000.0
la tensión en A es [N]  2549509.7567963926
el ángulo de la tensión en A es [deg]  11.309932474020215
para reducir de 5 a 2[m] en la vertical
la tensión horizontal aumenta en [%] 150.0 y la tensión en el punto A aumenta de [%] 145.9283823204821
la longitud del cable para saco de 5[m] 205.20533333333333 la longitud del cable para saco de 2[m] 200.85005653333332
(x^4) el saco del cable de 75[m] entre postes de 70[m] [-43.59680052  43.59680052 -11.87373786  11.87373786]
(x^2) el saco del cable de 75[m] entre postes de 70[m] [ 11.45643924 -11.45643924]


### CATENARIAS

NO SON PARÁBOLAS. La única carga es el peso mismo del cable.
<br>
![title](EST/E-cables-10.png)
<br>

Se tiene que considerar que:

$$\int \frac{\partial{x}}{\sqrt{x^2+1}}=ln(x+\sqrt{x^2+1})=sinh^{-1}x$$

Luego, tenemos una porción de la catenaria, donde $C$ es la distancia del punto más bajo hasta el inicio del eje horizontal y $S$ la longitud del cable que nos da el peso total $W$

<br>
![title](EST/E-cables-11.png)
<br>

$$T=T_0\sqrt{1+\frac{S^2}{C^2}}$$
$$\partial{x}=\frac{\partial{S}}{\sqrt{1-\frac{S^2}{C{2}}}}$$
$$\Longrightarrow S=Csinh(\frac{X}{C})$$
$$\Longrightarrow C=\frac{T_0}{w}$$
$$\Longrightarrow T=w\sqrt{C^2+S^2}$$
$$\Longrightarrow y=Ccosh(\frac{X}{C})$$
$$\Longrightarrow T=wy$$
$$\Longrightarrow y^2-S^2=C^2$$

#### EJERCICIO

Sea la altura al punto más bajo $h=20[m]$ y la carga del cable $w=50[N/m]$. Está entre A y B a la misma altura y $x=50[m]$, $AB=100[m]$. $$y_B=20+C[m]$$ Se tiene que:

$$y=Ccosh(\frac{x}{C})$$
$$\frac{20}{C}+1=cosh(\frac{x}{C})$$

In [58]:
x=50
N=20 #numero de valores
T=np.zeros((N,3))

#iterar los valores
C=np.linspace(66.5,67,N) #crear valores de C
#eval1
A=np.cosh(x/C)
#eval2
B=(20/C)+1
T[:,0]=C
T[:,1]=A
T[:,2]=B
print(T)

[[66.5         1.29623128  1.30075188]
 [66.52631579  1.29598604  1.30063291]
 [66.55263158  1.29574111  1.30051404]
 [66.57894737  1.29549648  1.30039526]
 [66.60526316  1.29525217  1.30027657]
 [66.63157895  1.29500816  1.30015798]
 [66.65789474  1.29476445  1.30003948]
 [66.68421053  1.29452105  1.29992107]
 [66.71052632  1.29427796  1.29980276]
 [66.73684211  1.29403517  1.29968454]
 [66.76315789  1.29379269  1.29956642]
 [66.78947368  1.29355051  1.29944838]
 [66.81578947  1.29330863  1.29933045]
 [66.84210526  1.29306706  1.2992126 ]
 [66.86842105  1.29282579  1.29909484]
 [66.89473684  1.29258482  1.29897718]
 [66.92105263  1.29234415  1.29885961]
 [66.94736842  1.29210378  1.29874214]
 [66.97368421  1.29186371  1.29862475]
 [67.          1.29162394  1.29850746]]
